feat: Add HttpClient to MakeAsync
morpher-ru/Yandex.Checkout.V3 pull request #50
Opened 2023-02-03 09:10 UTC by ipostanogov

Конструктор AsyncClient [ожидает](https://github.com/morpher-ru/Yandex.Checkout.V3/blob/0b1c45f947bcf10abf692478e264e6fa19c04651/Yandex.Checkout.V3/AsyncClient.cs#L16), что HttpClient сконфигурирован. В то же время нет метода, который бы конфигурировал сторонний HttpClient (например, полученный из [IHttpClientFactory](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests)). 

Предлагаю такой вариант.

2023-02-03 19:28 UTC, bzaar commented
А что мешает самому сконфигурировать HttpClient (полученный откуда бы то ни было) перед передачей его в конструктор AsyncClient?

2023-02-03 19:29 UTC, bzaar commented
И еще одно маленькое замечание - PR ломает бинарную совместимость, т.е. нельзя будет просто заменить одну DLL на другую. Хотя, так уже наверное никто не делает (я надеюсь).

2023-02-03 19:47 UTC, bzaar requested changes

2023-02-03 19:47 UTC, bzaar commented on Yandex.Checkout.V3/ClientExtensions.cs
> +            return new AsyncClient(httpClient, true);
В данной строке `true` означает, что для httpClient будет вызван Dispose() при вызове Dispose() для AsyncClient. Вы уверены, что хотите уничтожить httpClient, созданный IHttpClientFactory?

2023-02-03 19:47 UTC, bzaar commented on Yandex.Checkout.V3/ClientExtensions.cs
> +            return new AsyncClient(httpClient, true);
Предлагаю передавать true, только если внутри этого метода был вызван new HttpClient().

2023-02-04 03:59 UTC, ipostanogov commented on Yandex.Checkout.V3/ClientExtensions.cs
> +            return new AsyncClient(httpClient, true);
Добавил аргумент disposeOfHttpClient, установленный в false. Вернул бинарную совместимость.

2024-07-05 16:08 UTC, bzaar commented
В результате обсуждения принято решение этой проблемы, реализованное в PR #69. Данный PR закрываю.

2024-07-05 16:08 UTC, closed without merging